### ISSUE TITLE
Installer.sh 

### ISSUE THREAD

**Issue by adambenayoun** [sixninetynine/surrogate#11]
It seems that you're not prompting for all of the questions needed to run the script out of the box.
Was it on purpose to not ask for the main user password?

Additionally regarding the **mysql socket** location:
It seems that you're using a default but on my system it does not exist in that place. How about these options:

1. Try to guess the location of the sock based on certain parameters? ie: parse: my.cnf
2. Check if the sock file exists and if not then ask for the location?

**Comment by sixninetynine** [comment]
after looking into this ....... literally 2 years later

I see that the socket is configurable in surrogate.conf, I think that ought to suffice. most folks probably don't know the socket path off the top of their head when running the installer, yeah?

closing, reopen or submit a PR if you are unsatisfied with my assessment :)
