### ISSUE TITLE
crontab path is not correctly guessed

### ISSUE THREAD

**Issue by modir** [sixninetynine/surrogate#15]
The installer fails on installing a crontab entry. I get the following error messages:

./installer.sh: line 111: /root/surrogate-master/root: No such file or directory
./installer.sh: line 112: $CRONPATH: ambiguous redirect
./installer.sh: line 113: $CRONPATH: ambiguous redirect

The system is a CentOS 7.

**Comment by sixninetynine** [comment]
hey @modir 

this is [also fixed!](https://github.com/sixninetynine/surrogate/commit/8e17d37c19fb5a864fb002d2814f503f640bdbca)

enjoy
