### ISSUE TITLE
surrogate tries to delete files on the first run

### ISSUE THREAD

**Issue by modir** [sixninetynine/surrogate#16]
When I started surrogate I got this error message:

rm: cannot remove ‘/srv/backup/surrogate/backups/daily/Wed/full_2015-02-04_1730’: No such file or directory

I think it would be good if it is tested as well if this file really exists.

**Comment by sixninetynine** [comment]
hi @modir, sorry for the late update but I fixed this error with this [commit](https://github.com/sixninetynine/surrogate/commit/a9c71a47c82b6933703bf314161009c29235c82a)

enjoy!
